services:
  - type: web
    name: components-server
    plan: starter
    env: python
    region: frankfurt  # region should be same as your database region.
    buildCommand: "./backend/build.sh"
    startCommand: "gunicorn run:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
